import './globals.css'
import { Geist } from 'next/font/google'
import { ReduxProvider } from '~/redux/reduxProvider'
import ToastMessage from '~widgets/toastMessage'

const geistSans = Geist({
	subsets: ['latin'],
	variable: '--font-geist-sans',
	display: 'swap'
})

export const metadata = {
	title: 'My Shops',
	description: 'Generated by my-shops.com'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en' className='bg-[var(--background)] text-[var(--foreground)]'>
			<link rel='icon' href='/metaIcon.svg' sizes='any' />
			<body className={`${geistSans.variable} antialiased w-full min-h-screen`}>
				<ReduxProvider>
					<div className='w-full min-h-screen'>
						<div className='w-full h-20'>Header</div>
						<div className='w-full max-w-7xl mx-auto'>{children}</div>
					</div>
					<ToastMessage />
				</ReduxProvider>
			</body>
		</html>
	)
}
